const {test}=require('node:test'),a=require('node:assert/strict');require('./load-current.cjs');const M=globalThis.Mapping;
const pub=(db,text=M.DEMO)=>{const d=M.extract(text,db);d.identityConfirmed=true;db.drafts.push(d);M.publish(db,d);return d;};
const names=(db,ids)=>ids.map(id=>db.people.find(p=>p.id===id).name);
const EXP=/^(C-C|G-C|P-A(09|1\d)|J-C|CAP-J-C|E-(G-C|J-C|EV-C|PL)|EV-C|PL-|AN-C)/;
// V3.3 扩充样本的 ID；V3.0 存档同样不可能包含它们，模拟旧存档时必须一起剥离。
const EXP33=/^(C-D|G-D|P-D|J-D|CAP-J-D|E-(G-D|J-D|D01B))/;
const expanded=id=>EXP.test(id)||EXP33.test(id);

test('V3.1 扩充样本：4公司7项目26人，主线叙事不变',()=>{const db=M.seed();M.validateDatabase(db);a.equal(db.dataVersion,33);a.equal(db.companies.length,4);a.equal(db.projects.length,7);a.equal(db.people.length,26);a.deepEqual(M.query(db,{combat:true,chief:true}).map(p=>p.name),['顾航']);pub(db);a.deepEqual(M.query(db,{combat:true,chief:true}).map(p=>p.name),['林序','顾航']);});
test('扩充样本全部有来源且标为历史底库初始化，不计近30天新采集',()=>{const db=M.seed();const s=M.activityMetrics(db);a.equal(s.collected.length,0);a.equal(s.newEvents.length,0);for(const e of db.evidence.filter(e=>EXP.test(e.id)))a.equal(e.ingestionKind,'历史底库初始化');for(const j of db.jobs.filter(j=>EXP.test(j.id)))a.ok(M.fieldClaims(db,j.id,'membership').length);});

test('明确转岗需事件关联前后任职；履历先后保持待核验',()=>{const db=M.seed();let f=M.flows(db);a.equal(f.edges.find(e=>e.from==='G-C1'&&e.to==='G-C2').count,2);a.ok(!f.edges.some(e=>e.moves.some(m=>m.personId==='P-A01')));pub(db);f=M.flows(db);const lin=f.edges.find(e=>e.from==='G-A1'&&e.to==='G-A2').moves.find(m=>m.personId==='P-A01');a.ok(lin.inferred);a.equal(f.candidateEdges.find(e=>e.from==='G-B1'&&e.to==='G-A1').count,2);a.ok(!f.edges.some(e=>e.from==='G-B1'&&e.to==='G-A1'));});
test('同项目岗位变化不算流动；去向未收录不计入流动',()=>{const db=M.seed(),f=M.flows(db);a.ok(!f.edges.some(e=>e.from===e.to));a.deepEqual(names(db,f.exits.map(x=>x.personId)).sort(),['何川','程野','陆遥','顾航','裴安','卫楚','卫楚'].sort());a.equal(f.net['G-C1'].out,2);a.equal(f.net['G-C1'].candidateOut,1);a.equal(f.net['G-C1'].exit,4);});
test('待审核提案不进入流向与热力图',()=>{const db=M.seed(),before=JSON.stringify(M.flows(db));db.drafts.push(M.extract(M.DEMO,db));a.equal(JSON.stringify(M.flows(db)),before);});

test('健康度由字段证据直接计数；发布后出现推定边界与职责标准化',()=>{const db=M.seed();const h0=Object.fromEntries(M.health(db).map(x=>[x.key,x]));a.equal(h0.inferred.value,0);a.equal(h0.explicit.value,h0.explicit.total);pub(db);const h=Object.fromEntries(M.health(db).map(x=>[x.key,x]));a.equal(h.inferred.value,1);a.equal(h.explicit.total-h.explicit.value,1);a.ok(h.single.jobIds.length>0);a.equal(h.relations.value,2);});
test('隔离任职来源后健康度与明确流向同步重算',()=>{const db=M.seed();M.setSourceStatus(db,'E-J-C02',true,'待查','HRBP');a.equal(M.health(db).find(x=>x.key==='quarantine').value,1);a.equal(M.flows(db).edges.find(e=>e.from==='G-C1'&&e.to==='G-C2').count,1);});

test('热力图：人数按人员去重，带组以上人数单列，不计算稀缺度',()=>{const db=M.seed(),hm=M.heatmap(db),row=hm.rows.find(r=>r.project.id==='G-C1'),cell=row.cells.find(c=>c.domain==='战斗体系');a.equal(cell.count,2);a.equal(cell.leads,1);const t=hm.totals.find(t=>t.domain==='战斗体系');a.equal(t.people,M.query(db,{capability:'战斗体系'}).length);});
test('时间轴：星海纪元2025收缩后人数下降，并列出流出与去向未收录',()=>{const db=M.seed(),t=M.timeline(db,'G-C1'),y24=t.find(x=>x.year===2024),y25=t.find(x=>x.year===2025);a.ok(y24.count>y25.count);a.equal(y25.count,2);a.deepEqual(names(db,y25.outflow.map(m=>m.personId)).sort(),['沈砚','韩露'].sort());a.equal(y24.exits.length,1);a.ok(y25.events.some(e=>e.id==='EV-C1'));});

test('长名单：A层硬条件全部有证据；林序发布后进入A层',()=>{const db=M.seed(),need=M.LONGLIST_PRESETS.find(p=>p.id==='chief-combat');let r=M.longlist(db,need);a.deepEqual(r.filter(x=>x.tier==='A').map(x=>x.person.name),['顾航']);const shen=r.find(x=>x.person.name==='沈砚');a.equal(shen.tier,'B');a.ok(shen.gaps.some(g=>g.includes('主策')));a.ok(!r.some(x=>x.person.name==='何川'));pub(db);r=M.longlist(db,need);a.deepEqual(r.filter(x=>x.tier==='A').map(x=>x.person.name).sort(),['林序','顾航'].sort());const lin=r.find(x=>x.person.name==='林序');a.ok(lin.checks.some(c=>c.includes('推定')));a.ok(lin.hits.every(h=>h.evidenceIds.length));});
test('长名单：责任范围不足降级，每人都有意向未知提示，空需求报错',()=>{const db=M.seed(),r=M.longlist(db,{domains:['战斗体系'],minScope:3});const bai=r.find(x=>x.person.name==='白芷');a.equal(bai.tier,'B');a.ok(bai.gaps.some(g=>g.includes('低于')));a.ok(r.every(x=>x.checks.some(c=>c.includes('求职意向未知'))));a.throws(()=>M.longlist(db,{domains:[]}),/至少/);});

test('研判是判断层：保存不改变任何事实与查询，写入日志且不可被事实撤销误删',()=>{const db=M.seed();pub(db);const facts=JSON.stringify({jobs:db.jobs,claims:db.fieldClaims,rel:db.relationships}),q=M.query(db,{combat:true,chief:true}).length,ev=db.events.find(e=>e.draftId);M.saveAnalysis(db,ev.id,{priority:'P1',signal:'林序历史战斗轨迹补录',judgement:'可作为战斗带组方向的研究对象',action:'核验玄霄任期末年',window:'1个月',reviewBy:'2026-10-31'});a.equal(JSON.stringify({jobs:db.jobs,claims:db.fieldClaims,rel:db.relationships}),facts);a.equal(M.query(db,{combat:true,chief:true}).length,q);a.equal(db.logs.at(-1).type,'研判更新');a.equal(db.logs.at(-1).before,null);a.ok(M.analyses(db).some(x=>x.eventId===ev.id));M.validateDatabase(db);});
test('研判拒绝意向推断与缺字段；事件来源隔离后研判隐藏',()=>{const db=M.seed(),base={priority:'P0',signal:'s',judgement:'此人可挖性高',action:'a',window:'w'};a.throws(()=>M.saveAnalysis(db,'EV-C1',base),/意向/);a.throws(()=>M.saveAnalysis(db,'EV-C1',{...base,judgement:'',}),/均需填写/);a.throws(()=>M.saveAnalysis(db,'EV-C1',{...base,judgement:'j',priority:'P9'}),/优先级/);a.equal(M.analyses(db)[0].eventId,'EV-C1');M.setSourceStatus(db,'E-EV-C1',true,'待查','HRBP');a.ok(!M.analyses(db).some(x=>x.eventId==='EV-C1'));a.equal(M.linksFor(db,'G-C1').find(l=>l.id==='PL-1').processStatus,'待核验');});

test('人才池：跟进状态是工作记录，含负责人/复核日/历史；关键约束生效',()=>{const db=M.seed(),facts=JSON.stringify(db.jobs);a.ok(M.poolItems(db).some(i=>i.personId==='P-A10'&&i.overdue));M.poolAdd(db,'P-A17',{need:'云境战斗储备'});const m=db.poolMeta['P-A17'];a.equal(m.status,'待研究');a.equal(m.nextReview,M.addDays(db.observationDate,30));a.throws(()=>M.poolUpdate(db,'P-A17',{status:'可推荐给业务',owner:'HRBP',note:''}),/依据/);a.throws(()=>M.poolUpdate(db,'P-A17',{status:'待核验',owner:'HRBP',note:'强意向'}),/意向/);a.throws(()=>M.poolUpdate(db,'P-A17',{status:'已联系',owner:'HRBP'}),/状态/);M.poolUpdate(db,'P-A17',{status:'可推荐给业务',owner:'业务A',note:'云境战斗负责人经历已核对原文',nextReview:'2026-10-15'});a.equal(db.poolMeta['P-A17'].history.length,2);a.equal(JSON.stringify(db.jobs),facts);M.validateDatabase(db);M.poolRemove(db,'P-A17');a.ok(!db.poolMeta['P-A17']);});

test('V3.0 存档迁移：保留审核进度与日志，并入扩充样本，撤销旧变更不丢新样本',()=>{
 const db=M.seed();pub(db);
 const strip=o=>{for(const k of ['companies','projects','evidence','people','jobs','capabilities','events'])if(Array.isArray(o[k]))o[k]=o[k].filter(x=>!expanded(x.id));if(o.fieldClaims)o.fieldClaims=o.fieldClaims.filter(c=>!expanded(c.jobId));};
 strip(db);for(const l of db.logs)if(l.before)strip(l.before);delete db.projectLinks;delete db.analyses;delete db.poolMeta;delete db.poolSeeded;db.pool=[];db.dataVersion=30;
 const raw=JSON.stringify(db),state=M.loadState({getItem:k=>k===M.KEY?raw:null});a.equal(state.migrationRequired,true);a.equal(db.people.length,8);
 const next=M.migrateDatabase(db);a.equal(JSON.stringify(db),raw);a.equal(next.dataVersion,33);a.equal(next.people.length,26);a.equal(next.logs.length,db.logs.length);a.deepEqual(M.query(next,{combat:true,chief:true}).map(p=>p.name),['林序','顾航']);a.equal(next.analyses.length,3);a.equal(next.projectLinks.length,4);M.validateDatabase(next);
 M.undo(next);a.equal(next.people.length,26);a.ok(next.jobs.some(j=>j.id==='J-C01'));a.deepEqual(M.query(next,{combat:true,chief:true}).map(p=>p.name),['顾航']);M.validateDatabase(next);
 a.equal(JSON.stringify(M.migrateDatabase(next)),JSON.stringify(next));
});
test('导入校验拒绝伪造的项目关系引文与非法人才池状态',()=>{let db=M.seed();db.projectLinks[0].quote='不存在的原句';a.throws(()=>M.validateDatabase(db),/项目关系/);db=M.seed();db.poolMeta['P-A10'].status='已发offer';a.throws(()=>M.validateDatabase(db),/人才池/);db=M.seed();db.analyses[0].kind='事实';a.throws(()=>M.validateDatabase(db),/研判/);});
