const {chromium}=require('playwright-core');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),a=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),out=path.join(base,'screenshots-v32');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const results=[];try{
 for(const mode of ['online','offline','offline-no-storage']){
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 if(mode==='offline-no-storage')await context.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Disabled','SecurityError')}}));
 if(mode!=='online')await context.setOffline(true);
 const p=await context.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:8767/'))external.push(r.url());});
 const click=sel=>p.locator(sel).first().click(),nav=name=>click(`[data-action="nav"][data-page="${name}"]`),close=async()=>{while(await p.locator('#detail').isVisible())await click('#detail [data-action="close"]');};
 await p.goto(mode==='online'?'http://127.0.0.1:8767/':pathToFileURL(path.join(base,'MMO_Mapping_V3.4.0_独立演示.html')).href);await p.locator('#quickSearch').waitFor();
 await nav('requirements');a.match(await p.locator('.content').innerText(),/尚未保存需求/);await click('[data-action="reqNew"]');await p.locator('#longlistForm [name="title"]').fill('云境主策储备（演示）');await click('[data-action="reqSave"]');await p.locator('#requirementSaveForm [name="requester"]').fill('业务甲（演示）');await p.locator('#requirementSaveForm button.btn').click();
 a.match(await p.locator('[data-tier="A"] h2').innerText(),/1 人/);a.match(await p.locator('.content').innerText(),/逐人覆盖 26\/26/);await click('[data-action="reqDeliver"]');a.match(await p.locator('#detailBody').innerText(),/口径 v1/);
 await p.locator('#requirementFeedbackForm [name="personId"]').selectOption('P-A07');await p.locator('#requirementFeedbackForm [name="decision"]').selectOption('同意接触');await p.locator('#requirementFeedbackForm [name="reason"]').fill('已核对主策和战斗经历，建议由招聘同事进一步研究。');await p.locator('#requirementFeedbackForm button.btn').click();a.match(await p.locator('#detailBody').innerText(),/已核对主策和战斗经历/);await close();
 await click('[data-tier="A"] [data-action="poolNeed"]');
 const first=await p.evaluate(()=>JSON.parse(JSON.stringify(db.requirements[0])));a.deepEqual(first.deliveries[0].tierA,['P-A07']);
 await p.locator('#longlistForm [name="chief"]').uncheck();await click('[data-action="reqDeliver"]');a.match(await p.locator('#toast').innerText(),/先保存新版本/);await click('[data-action="reqSave"]');await p.locator('#requirementSaveForm [name="reason"]').fill('先研究战斗带组经历，不要求已有主策头衔；仅作为需求讨论。');await p.locator('#requirementSaveForm button.btn').click();a.match(await p.locator('.content').innerText(),/口径 v2/);a.ok((await p.evaluate(()=>db.requirements[0].calibrations.length))>0);await click('[data-action="reqDeliver"]');await close();
 const state=await p.evaluate(()=>JSON.parse(JSON.stringify(db)));a.equal(state.requirements[0].deliveries.length,2);a.deepEqual(state.requirements[0].deliveries[0],first.deliveries[0]);
 const download=p.waitForEvent('download');await click('[data-action="llExport"]');const downloaded=await download;const csv=fs.readFileSync(await downloaded.path(),'utf8');a.match(csv,/未入选\/缺口原因/);a.ok(csv.split('\r\n').length===27);
 await p.screenshot({path:path.join(out,mode+'-longlist.png'),fullPage:true});
 await click('[data-tier="A"] [data-action="persona"]');a.match(await p.locator('#detailBody').innerText(),/人才画像/);await close();
 // V3.3 organisation analysis, at desktop width while the sidebar is still expanded.
 await nav('org');const orgText=await p.locator('.content').innerText();
 a.match(orgText,/层级倒挂/);a.match(orgText,/同名不同人/);a.match(orgText,/沧溟/);a.match(orgText,/扩样 mapping/);
 a.ok(!/强意向|可挖性|想跳槽|在看机会/.test(orgText),'组织分析页不得出现意向推断');
 a.ok(!/单点/.test(await p.locator('.org-play').first().innerText()),'均匀薄的样本不应把收录缺口报成单点风险');
 await click('[data-action="bench"]');a.match(await p.locator('#detailBody').innerText(),/不是该项目的真实编制/);await close();
 await p.evaluate(()=>openModal('persona','P-D08'));const pk=await p.locator('#detailBody').innerText();a.match(pk,/成长节奏/);a.match(pk,/求职意向未知/);a.match(pk,/2021 年「参与」→ 2023 年/);await close();
 await p.evaluate(()=>openModal('persona','P-D01'));a.match(await p.locator('#detailBody').innerText(),/画像不成立/);await close();
 await click('.org-play [data-action="person"]');await click('#detailBody [data-action="persona"]');a.match(await p.locator('#detailBody').innerText(),/人才画像/);await close();
 await p.screenshot({path:path.join(out,mode+'-org.png'),fullPage:true});
 // V3.4 audited flow: confirmed, candidate, concurrent and pending destinations are separate.
 await nav('flow');const flowText=await p.locator('.content').innerText();a.match(flowText,/明确转岗/);a.match(flowText,/履历先后 · 待核验/);a.match(flowText,/同期跨项目/);a.match(flowText,/去向未收录/);a.match(flowText,/确认净值/);
 await click('table [data-action="flowEdge"][data-id^="candidate|"]');a.match(await p.locator('#detailBody').innerText(),/不参与净流量/);a.ok(await p.locator('#detailBody [data-action="claim"]').count()>0);await close();
 await click('[data-action="flowConcurrent"]');a.match(await p.locator('#detailBody').innerText(),/同期重叠不自动判定/);await close();
 await click('[data-action="flowProject"][data-id="G-D1"]');a.match(await p.locator('.content').innerText(),/当前筛选：沧溟/);await click('[data-action="flowProject"][data-id=""]');
 await p.screenshot({path:path.join(out,mode+'-flow.png'),fullPage:true});
 await nav('requirements');await click('[data-action="reqPool"]');a.match(await p.locator('.pool-card').first().innerText(),/顾航/);
 await nav('requirements');await click('[data-action="reqOpen"]');await click('[data-action="reqHistory"]');await click('[data-action="reqRestore"][data-version="1"]');await p.locator('#requirementRestoreForm [name="reason"]').fill('恢复原始岗位口径，保留前次研究记录');await p.locator('#requirementRestoreForm button.btn').click();a.equal(await p.evaluate(()=>db.requirements[0].version),3);
 await p.evaluate(()=>{M.setSourceStatus(db,'E-J-A08',true,'来源复核（演示）','HRBP');save();render();});await click('[data-action="reqHistory"]');await click('[data-action="reqDelivery"]');a.match(await p.locator('#detailBody').innerText(),/历史依据已有变更/);await close();
 await nav('data');const exported=p.waitForEvent('download');await click('[data-action="exportV2"]');const json=JSON.parse(fs.readFileSync(await (await exported).path(),'utf8'));a.equal(json.requirements[0].businessFeedback.length,1);await p.locator('[name="json"]').fill(JSON.stringify(json));await p.locator('#importForm button.btn').click();await click('[data-action="importConfirm"]');
 if(mode!=='offline-no-storage'){await p.reload();await p.locator('#quickSearch').waitFor();a.equal(await p.evaluate(()=>db.requirements[0].version),3);}
 await p.setViewportSize({width:390,height:844});for(const name of ['requirements','longlist','pool','org','flow']){await nav(name);a.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,name+' mobile overflow');}
 await nav('requirements');await p.screenshot({path:path.join(out,mode+'-mobile.png'),fullPage:true});
 a.deepEqual(errors,[]);a.deepEqual(external,[]);results.push({mode,status:'passed',version:3,deliveries:2,feedback:1,allPeopleExplained:26,consoleErrors:errors,externalRequests:external.length,mobileWidth:390});await context.close();
 }
 // Genuine V3.1 backup: preview must not write before confirmation, then backup first.
 const c=await browser.newContext();const p=await c.newPage();await p.goto('http://127.0.0.1:8767/');const old=await p.evaluate(()=>{const v=M.seed();delete v.requirements;v.dataVersion=31;localStorage.setItem(M.KEY,JSON.stringify(v));return JSON.stringify(v);});await p.reload();await p.locator('.migration').waitFor();a.match(await p.locator('h1').innerText(),/迁移预览/);a.equal(await p.evaluate(()=>localStorage.getItem(M.KEY)),old);await p.locator('[data-action="upgrade"]').click();a.equal(await p.evaluate(()=>db.dataVersion),33);a.equal(await p.evaluate(()=>localStorage.getItem(localStorage.getItem('mmo-mapping-v2-last-backup'))),old);await c.close();
 const cx=await browser.newContext(),pa=await cx.newPage();await pa.goto('http://127.0.0.1:8767/');await pa.evaluate(()=>{M.saveRequirement(db,null,{title:'并发测试需求（演示）',conditions:{domains:['战斗体系'],minScope:2,chief:true,genre:''},owner:'HRBP',requester:'业务方',status:'开放',reason:''});save();});const pb=await cx.newPage();await pb.goto('http://127.0.0.1:8767/');await pa.evaluate(()=>{M.setSourceStatus(db,'E-J-A08',true,'并发来源核验','HRBP');M.deliverRequirement(db,db.requirements[0].id);save();});const protectedRaw=await pa.evaluate(()=>localStorage.getItem(M.KEY));await pb.locator('[data-action="nav"][data-page="requirements"]').first().click();await pb.locator('[data-action="reqOpen"]').click();await pb.locator('#longlistForm [name="title"]').fill('陈旧页面的改名（演示）');await pb.locator('[data-action="reqSave"]').click();await pb.locator('#requirementSaveForm [name="reason"]').fill('修改需求名');await pb.locator('#requirementSaveForm button.btn').click();a.equal(await pb.evaluate(()=>localStorage.getItem(M.KEY)),protectedRaw);a.match(await pb.evaluate(()=>storageError),/其他标签页/);
 const before=await pa.evaluate(()=>JSON.stringify(db));await pa.evaluate(()=>{const next=M.clone(db);M.saveRequirement(next,null,{title:'导入后新增需求',conditions:{domains:['战斗体系'],minScope:1,chief:false,genre:''},owner:'HRBP',requester:'业务方',status:'开放',reason:''});const rawStorage=storage;storage={getItem:k=>rawStorage.getItem(k),setItem(k,v){if(k===M.KEY)throw new DOMException('Quota exceeded','QuotaExceededError');rawStorage.setItem(k,v);}};openModal('import','',{data:next});});await pa.locator('[data-action="importConfirm"]').click();a.equal(await pa.evaluate(()=>JSON.stringify(db)),before);a.match(await pa.locator('#toast').innerText(),/恢复失败，原数据未替换/);await cx.close();
 fs.writeFileSync(path.join(base,'tests/v32-browser-results.json'),JSON.stringify({results,migration:'passed',staleTabProtection:'passed',failedImportAtomicity:'passed'},null,2));console.log(JSON.stringify({results,migration:'passed',staleTabProtection:'passed',failedImportAtomicity:'passed'},null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
