const assert=require('node:assert/strict');require('./model.js');const M=globalThis.Mapping;let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name);throw e;}}
function draft(db,text=M.DEMO){const d=M.extract(text,db);db.drafts.push(d);return d;}
function publish(db,text=M.DEMO){const d=draft(db,text);d.identityConfirmed=true;return M.publish(db,d);}
test('V2基线：两公司三项目八人，仅顾航命中',()=>{const db=M.seed();assert.equal(db.people.length,8);assert.equal(db.companies.length,2);assert.equal(db.projects.length,3);assert.deepEqual(M.query(db,{combat:true,chief:true}).map(p=>p.name),['顾航']);M.validateDatabase(db);});
test('阶段与任职一致，每个实体有依据',()=>{const db=M.seed();for(const j of db.jobs){const p=db.projects.find(p=>p.id===j.projectId);assert.ok(j.start>=p.start);assert.ok(p.phases.some(s=>M.active(s,j.start)));assert.ok(j.evidenceIds.every(id=>db.evidence.some(e=>e.id===id)));}for(const r of db.relationships)assert.ok(r.evidenceIds.length);});
test('待审核隔离',()=>{const db=M.seed();draft(db);assert.equal(M.query(db,{combat:true,chief:true}).length,1);assert.equal(db.jobs.length,10);});
test('人审前禁止发布且事务不污染数据',()=>{const db=M.seed(),d=draft(db),before=M.clone(db);assert.throws(()=>M.publish(db,d),/人工确认/);assert.deepEqual(db,before);});
test('既有云境经历提案识别为补证据',()=>{const db=M.seed(),d=draft(db);assert.equal(d.personId,'P-A01');assert.equal(d.facts[2].comparison.targetId,'J-A01');assert.equal(d.facts[2].comparison.action,'已有一致 / 补证据');});
test('新故事发布：2新增1更新1暂缓，人员与主策不重复',()=>{const db=M.seed();const s=publish(db);assert.deepEqual(s,{added:2,updated:1,deferred:1,rejected:0});assert.equal(db.people.length,8);assert.equal(db.jobs.length,12);assert.equal(db.jobs.filter(j=>j.personId==='P-A01'&&j.projectId==='G-A2').length,1);assert.deepEqual(M.query(db,{combat:true,chief:true}).map(p=>p.name),['林序','顾航']);assert.equal(db.jobs.find(j=>j.id==='J-A01').evidenceIds.length,2);assert.equal(db.events.length,2);});
test('玄霄历史组织与跨公司轨迹同步',()=>{const db=M.seed();publish(db);assert.ok(M.projectPeople(db,'G-A1',2022).includes('P-A01'));assert.ok(!M.projectPeople(db,'G-A1',2024).includes('P-A01'));assert.equal(M.projectPeople(db,'G-A2',2024).filter(x=>x==='P-A01').length,1);assert.ok(M.projectPeople(db,'G-B1',2020).includes('P-A01'));});
test('第一条材料不能声明正式组长',()=>{const db=M.seed();publish(db);assert.equal(M.query(db,{text:'战斗组长'}).some(p=>p.id==='P-A01'),false);const j=db.jobs.find(j=>j.personId==='P-A01'&&j.projectId==='G-A1');assert.ok(!M.roleAt(j,2021).includes('组长'));});
test('拒绝关系不影响三条任职处理',()=>{const db=M.seed(),d=draft(db);d.identityConfirmed=true;d.facts[3].decision='reject';const s=M.publish(db,d);assert.equal(s.rejected,1);assert.equal(M.query(db,{combat:true,chief:true}).length,2);assert.equal(db.relationships.length,3);});
test('拒绝能力标签不自动从职位生成能力',()=>{const db=M.seed(),d=draft(db);d.identityConfirmed=true;d.facts[0].value.capability=false;d.facts[1].value.capability=false;M.publish(db,d);assert.equal(M.query(db,{combat:true,chief:true}).length,1);});
test('重复提案只补同源依据，不重复任职或来源',()=>{const db=M.seed();publish(db);const count=db.evidence.length,jobs=db.jobs.length;const d=draft(db);d.identityConfirmed=true;M.publish(db,d);assert.equal(db.jobs.length,jobs);assert.equal(db.evidence.length,count);});
test('补充头衔仅对2022—2023有效',()=>{const db=M.seed();publish(db);publish(db,M.SUPPLEMENT);const j=db.jobs.find(j=>j.personId==='P-A01'&&j.projectId==='G-A1');assert.ok(!M.roleAt(j,2021).includes('组长'));assert.ok(M.roleAt(j,2022).includes('组长'));assert.equal(db.jobs.filter(x=>x.personId==='P-A01').length,3);assert.notEqual(j.factStatus,'已独立交叉核验');});
test('第二条先输入时不盲建历史岗位',()=>{const db=M.seed();const s=publish(db,M.SUPPLEMENT);assert.equal(s.deferred,1);assert.equal(db.jobs.length,10);});
test('虚线不参与正式汇报链；含专门原文线索',()=>{const db=M.seed();assert.equal(M.reports(db).length,0);assert.ok(db.evidence.find(e=>e.id==='E-R-A1').text.includes('向许舟汇报'));assert.equal(M.projectRelations(db,'G-A2',2024).length,1);assert.equal(M.projectRelations(db,'G-A2',2025).length,2);});
test('模糊线索不能转实线；明确补充才可确认',()=>{const db=M.seed();assert.throws(()=>M.reviewRelation(db,'R-A1','confirm','核对','林序向许舟汇报方案'),/补充明确/);M.reviewRelation(db,'R-A1','confirm','新增直接关系的虚构材料','虚构材料：2024年起林序直接向许舟汇报，行政关系为直接上下级。');assert.equal(M.reports(db).length,1);assert.equal(db.jobs.length,10);assert.equal(db.relationships[0].factStatus,M.SINGLE);});
test('拒绝虚线保留人物任职并写审计',()=>{const db=M.seed();M.reviewRelation(db,'R-A1','reject','无明确行政依据');assert.equal(M.projectRelations(db,'G-A2',2024).length,0);assert.equal(db.people.length,8);assert.equal(db.jobs.length,10);assert.equal(db.logs.length,1);});
test('同年交接须理由，跨项目兼职仍待核验',()=>{const db=M.seed(),d=draft(db);d.identityConfirmed=true;d.facts[1].value.end=2024;const s=M.publish(db,d);assert.equal(s.deferred,2);const db2=M.seed(),d2=draft(db2);d2.identityConfirmed=true;d2.facts[1].value.end=2024;d2.facts[1].overlapResolution='transition';d2.facts[1].reviewNote='2024为迁移年，月份未知';const s2=M.publish(db2,d2);assert.equal(s2.added,2);});
test('跨经历与同段匹配语义不同',()=>{const db=M.seed();publish(db);assert.equal(M.query(db,{combat:true,chief:true,mode:'any'}).length,2);assert.equal(M.query(db,{combat:true,chief:true,mode:'same'}).length,0);});
test('30天窗口以观察日计算且排除未来',()=>{const db=M.seed(),base=M.recentEvidence(db).length;db.evidence.push({...db.evidence[0],id:'X',collected:'2026-08-23'},{...db.evidence[0],id:'Y',collected:'2026-09-23'});assert.equal(M.recentEvidence(db).length,base);db.observationDate='2026-09-23';assert.ok(M.recentEvidence(db).some(e=>e.id==='Y'));});
test('撤销恢复正式事实但保留证据与日志',()=>{const db=M.seed(),ec=db.evidence.length;publish(db);M.undo(db);assert.equal(db.jobs.length,10);assert.equal(db.evidence.length,ec+1);assert.equal(db.logs.length,2);assert.equal(M.query(db,{combat:true,chief:true}).length,1);});
test('本地序列化后结果一致',()=>{const db=M.seed();publish(db);const copy=JSON.parse(JSON.stringify(db));M.validateDatabase(copy);assert.deepEqual(M.query(copy,{combat:true,chief:true}),M.query(db,{combat:true,chief:true}));});
test('V1原始存储不改写；加载V2需显式选择',()=>{const raw=JSON.stringify({schema:1,people:[{id:'legacy'}]}),data=new Map([[M.LEGACY_KEY,raw]]),storage={getItem:k=>data.get(k)||null};const state=M.loadState(storage);assert.equal(state.needsChoice,true);assert.equal(data.get(M.LEGACY_KEY),raw);assert.equal(data.has(M.KEY),false);});
test('未知材料与非法导入有明确错误',()=>{assert.throws(()=>M.extract('今天好天气',M.seed()),/离线模拟/);assert.throws(()=>M.validateDatabase({schema:1}),/V2/);const d=M.seed();d.jobs[0].projectId='不存在';assert.throws(()=>M.validateDatabase(d),/引用/);});
console.log(`${passed} V2 domain tests passed`);
